dataset:
  train_root_dir: "F:\\research\\data\\small_imagenet_object_loc\\train"
  val_root_dir: "F:\\research\\data\\small_imagenet_object_loc\\val"
  classes_names_path: "F:\\research\\data\\small_imagenet_object_loc\\classes_names.txt"

model_hparams:
  num_channels: 3
  pixel_unshuffle_scale_factors: [2, 2, 2, 2]
  embedding_dim: 768
  filter_size: 0
  energy_ratio: 0.990
  qkv_dim: 64
  mlp_hidden_size: 3072
  n_layers: 12
  n_heads: 12
  n_classes: 6

train_hparams:
    lr: 1e-4
    alpha: 1.0
    train_batch_size: 24
    val_batch_size: 24
    num_workers: 6
    max_epoch: 20
    accelerator: "cuda"

logging:
  logging_step: 100