dataset:
  train_root_dir: "F:\\research\\data\\small_imagenet_object_loc\\train"
  val_root_dir: "F:\\research\\data\\small_imagenet_object_loc\\val"
  classes_names_path: "F:\\research\\data\\small_imagenet_object_loc\\classes_names.txt"


model_hparams:
  wavelet: 'haar'
  bit_planes: 2
  final_threshold: 0.125
  embedding_dim: 768
  qkv_dim: 64
  mlp_hidden_size: 3072
  n_layers: 12
  n_heads: 12
  n_classes: 6

  max_seq_len: 1024

train_hparams:
    lr: 1e-4
    alpha: 1.0
    train_batch_size: 2
    val_batch_size: 2
    num_workers: 6
    max_epoch: 4
    accelerator: "cuda"

logging:
  logging_step: 100